# Generated by Django 4.1.3 on 2022-11-16 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import osm_field.fields
import osm_field.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_lat',
            field=osm_field.fields.LatitudeField(default=45, validators=[osm_field.validators.validate_latitude]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_lon',
            field=osm_field.fields.LongitudeField(default=25, validators=[osm_field.validators.validate_longitude]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=osm_field.fields.OSMField(lat_field='location_lat', lon_field='location_lon'),
        ),
    ]
