# Generated by Django 4.1.2 on 2022-10-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_location_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
