# Generated by Django 4.1.2 on 2022-10-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friend_list',
            new_name='friends',
        ),
    ]
