# Generated by Django 4.1.2 on 2022-10-28 09:30

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_rename_friend_list_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='prieteni', to='Posts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='user', editable=False, populate_from='user'),
        ),
    ]
